apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search.fullname" . }}
  labels:
    {{- include "search.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "search.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "search.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "search.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env: 
          - name: RANKING_URL
            value: {{.Values.global.rankingUrl}}
          - name: REVIEW_URL
            value: {{.Values.global.reviewUrl}}
          - name: PHOTO_URL
            value: {{.Values.global.photoUrl}}
          - name: PROFILE_URL
            value: {{.Values.global.profileUrl}}
          - name: DB_USER
            value: {{.Values.global.db.user}}
          - name: DB_NAME
            value: {{.Values.global.db.name}}
          - name: DB_PASSWORD
            value: {{.Values.global.db.password}}
          - name: DB_HOST
            value: {{.Values.global.db.host}}
          - name: DB_PORT  
            value: "{{.Values.global.db.port}}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
